import Head from "next/head";
import { NextPage } from "next";
import { useRouter } from "next/router";

import FormLogin from "@/components/FormLogin";
import GlobalStyles from "@/components/GlobalStyles";
import useBreadcrumbs from "@/hooks/useBreadcrumbs";

export interface LoginProps {}

const Login : NextPage = () => {
    const router = useRouter();
    const newRouter = useBreadcrumbs(router);

    return (
        <>
            <Head>
                <title>{newRouter[newRouter.length - 1].title} - HoBa</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <GlobalStyles>
                    <FormLogin />
                </GlobalStyles>
            </main>
        </>
    );
};

export default Login;
