import Head from "next/head";
import { useRouter } from "next/router";

import useBreadcrumbs from "@/hooks/useBreadcrumbs";
import GlobalStyles from "@/components/GlobalStyles";
import FormBookDetail from "@/components/FormBookDetail";
import { GetServerSideProps, NextPage } from "next";
import { getBookByLink } from "@/lib/api";

export interface BookDetailProps {
    book?: any
}

const BookDetail : NextPage<BookDetailProps> = ({ book }) => {
    const router = useRouter();
    const newRouter = useBreadcrumbs(router);

    console.log(book)

    return (
        <>
            <Head>
                <title>{newRouter[newRouter.length - 1].title} - HoBa</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <GlobalStyles>
                    {book ? <FormBookDetail book={book}/> : <p>Sách lỗi</p>}
                </GlobalStyles>
            </main>
        </>
    );
};

export const getServerSideProps : GetServerSideProps = async (context) => {

    const book = await getBookByLink(context.query.link);

    return {
        props: {
            book: book.data.book || null
        }
    }

}

export default BookDetail;
