import Head from "next/head";

import GlobalStyles from "@/components/GlobalStyles";
// import { useSelector } from "react-redux";
import FormHome from "@/components/FormHome";
import { GetServerSideProps, NextPage } from "next";
import { getBooksByPage } from "@/lib/api";

interface HomeProps {
    books?: any
}

const Home : NextPage<HomeProps> = ({ books }) => {
    // const { currentUser } = useSelector((state: any) => state.user);


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <GlobalStyles>
                    <FormHome books={books}/>
                </GlobalStyles>
            </main>
        </>
    );
}

export const getServerSideProps : GetServerSideProps = async (context) => {

    const books = await getBooksByPage(context.query.page);

    return {
        props: {
            books: books.data.books || null
        }
    }

}

export default Home;