import Head from "next/head";

import GlobalStyles from "@/components/GlobalStyles";
import { useSelector } from "react-redux";

export default function Home() {
    const { currentUser } = useSelector((state: any) => state.user);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <GlobalStyles>
                    <p>{JSON.stringify(currentUser)}</p>
                </GlobalStyles>
            </main>
        </>
    );
}
