import Head from "next/head";
import { useRouter } from "next/router";
import useBreadcrumbs from "@/hooks/useBreadcrumbs";
import FormCreatorBook from "@/components/FormCreatorBook";


export interface CreatorProps {}

const Creator= () => {
    const router = useRouter();
    const newRouter = useBreadcrumbs(router);

    return (
        <>
            <Head>
                <title>{newRouter[newRouter.length - 1].title} - HoBa</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <FormCreatorBook title="Tin tức mới" description="Các hoạt động gần đây nhất"/>
            </main>
        </>
    );
};

export default Creator;
