import Head from "next/head";
import { useRouter } from "next/router";
import useBreadcrumbs from "@/hooks/useBreadcrumbs";

import FormCreatorBook from "@/components/FormCreatorBook";

export interface CreatorBookProps {}

const CreatorDrafts= () => {
    const router = useRouter();
    const newRouter = useBreadcrumbs(router);

    return (
        <>
            <Head>
                <title>{newRouter[newRouter.length - 1].title} - HoBa</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <FormCreatorBook
                    tab="drafts"
                    title="Các bản thảo"
                    description="Đây là tập hợp danh sách các bản thảo chưa xuất bản của bạn"
                />
            </main>
        </>
    );
};

export default CreatorDrafts;
