import Head from "next/head";
import { useRouter } from "next/router";
import useBreadcrumbs from "@/hooks/useBreadcrumbs";

import FormCreatorBook from "@/components/FormCreatorBook";
import ContentFormDraftsNew from "@/components/FormCreatorBook/ContentFormDraftsNew";

export interface CreatorBookProps {}

const CreatorBook = () => {
    const router = useRouter();
    const newRouter = useBreadcrumbs(router);

    return (
        <>
            <Head>
                <title>{newRouter[newRouter.length - 1].title} - HoBa</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <FormCreatorBook
                    tab="drafts/new"
                    title="Thêm bản thảo"
                    description="Bạn có thể thêm bản thảo và xuất bản nó ngay lập tức ở đây, hoặc đơn giản chỉ muốn viết một đoạn và để nó tự lưu lại"
                >
                    <ContentFormDraftsNew />
                </FormCreatorBook>
            </main>
        </>
    );
};

export default CreatorBook;
