import Head from "next/head";
import { NextPage } from "next";
import { useRouter } from "next/router";
import axios from "axios";

import useBreadcrumbs from "@/hooks/useBreadcrumbs";
import FormCreatorBook from "@/components/FormCreatorBook";
import ContentFormMyBooks from "@/components/FormCreatorBook/ContentFormMyBooks";

export interface CreatorBooksProps {
    books?: any
}

const CreatorBooks : NextPage<CreatorBooksProps> = ({ books }) => {
    const router = useRouter();
    const newRouter = useBreadcrumbs(router);

    console.log(books)

    return (
        <>
            <Head>
                <title>{newRouter[newRouter.length - 1].title} - HoBa</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <FormCreatorBook
                    tab="books"
                    title="Truyện của tôi"
                    description="Danh sách các truyện bạn đã đăng"
                >
                    {/* {books ? <ContentFormMyBooks books={books} /> : <p>Bạn chưa đăng tải truyện nào</p>} */}
                </FormCreatorBook>
            </main>
        </>
    );
};

export async function getServerSideProps({ context } : any) {

    console.log(context)

    const resMyBooks = await axios.get('/api/books');

    return {
        props: {
            books: resMyBooks.data.books || null
        },
    }
}

export default CreatorBooks;
