import Head from "next/head";
import { useRouter } from "next/router";
import useBreadcrumbs from "@/hooks/useBreadcrumbs";

import FormCreatorBook from "@/components/FormCreatorBook";

export interface CreatorBookProps {}

const CreatorBook= () => {
    const router = useRouter();
    const newRouter = useBreadcrumbs(router);

    return (
        <>
            <Head>
                <title>{newRouter[newRouter.length - 1].title} - HoBa</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <FormCreatorBook
                    tab="books/issues"
                    title="Báo lỗi"
                    description="Dù báo lỗi đúng hay sai nhớ đều phải trả lời để BTV có thể đóng báo lỗi"
                />
            </main>
        </>
    );
};

export default CreatorBook;
