import Head from "next/head";
import { useRouter } from "next/router";
import useBreadcrumbs from "@/hooks/useBreadcrumbs";

import FormCreatorBook from "@/components/FormCreatorBook";
import ContentFormNewBook from "@/components/FormCreatorBook/ContentFormNewBook";

export interface CreatorBookProps {}

const CreatorBook= () => {
    const router = useRouter();
    const newRouter = useBreadcrumbs(router);

    return (
        <>
            <Head>
                <title>{newRouter[newRouter.length - 1].title} - HoBa</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <FormCreatorBook
                    tab="books/new"
                    title="Thêm truyện mới"
                    description="Bắt đầu sáng tạo thế giới của riêng bạn"
                >
                    <ContentFormNewBook />
                </FormCreatorBook>
            </main>
        </>
    );
};

export default CreatorBook;
